using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ClassicUO.SourceGenerators
{
    [Generator]
    public class SqlSettingGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = @"// <auto-generated/>
using System;

namespace ClassicUO.Configuration
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class SqlSettingAttribute : Attribute
    {
        public SqlSettingAttribute(SettingsScope scope, string key, object defaultValue = null)
        {
            Scope = scope;
            Key = key;
            DefaultValue = defaultValue;
        }

        public SettingsScope Scope { get; }
        public string Key { get; }
        public object DefaultValue { get; }
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("SqlSettingAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            IncrementalValuesProvider<SqlSettingModel> properties = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "ClassicUO.Configuration.SqlSettingAttribute",
                    predicate: static (node, _) => node is PropertyDeclarationSyntax,
                    transform: static (ctx, _) => GetModel(ctx))
                .Where(static m => m != null);

            context.RegisterSourceOutput(properties.Collect(), Generate);
        }

        private static SqlSettingModel GetModel(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IPropertySymbol prop)
                return null;

            INamedTypeSymbol containingType = prop.ContainingType;
            if (containingType?.Name != "Profile")
                return null;

            AttributeData attr = ctx.Attributes[0];
            if (attr.ConstructorArguments.Length < 3)
                return null;

            // Argument 0: SettingsScope enum value (int ordinal)
            if (attr.ConstructorArguments[0].Value is not int scopeOrdinal)
                return null;

            // Argument 1: key string
            if (attr.ConstructorArguments[1].Value is not string key)
                return null;

            // Argument 2: default value (typed constant, boxed)
            object defaultRaw = attr.ConstructorArguments[2].Value;

            string containingNamespace = containingType.ContainingNamespace?.ToDisplayString() ?? "ClassicUO.Configuration";
            string jsonKey = ToSnakeCase(prop.Name);

            bool isEnum = prop.Type.TypeKind == TypeKind.Enum;

            if (isEnum)
            {
                string enumTypeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return new SqlSettingModel
                {
                    PropertyName = prop.Name,
                    TypeName = enumTypeName,
                    ScopeOrdinal = scopeOrdinal,
                    Key = key,
                    JsonKey = jsonKey,
                    DefaultValueLiteral = BuildEnumDefaultLiteral(enumTypeName, defaultRaw),
                    ContainingNamespace = containingNamespace,
                    IsEnum = true,
                    IsUnsupportedType = false
                };
            }

            string typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            string fullTypeName = prop.Type.SpecialType != SpecialType.None
                ? GetPrimitiveTypeName(prop.Type.SpecialType)
                : typeName;

            if (!IsSupportedType(fullTypeName))
            {
                return new SqlSettingModel
                {
                    PropertyName = prop.Name,
                    TypeName = fullTypeName,
                    ScopeOrdinal = scopeOrdinal,
                    Key = key,
                    JsonKey = jsonKey,
                    DefaultValueLiteral = "default",
                    ContainingNamespace = containingNamespace,
                    IsUnsupportedType = true
                };
            }

            string defaultLiteral = BuildDefaultLiteral(fullTypeName, defaultRaw);

            return new SqlSettingModel
            {
                PropertyName = prop.Name,
                TypeName = fullTypeName,
                ScopeOrdinal = scopeOrdinal,
                Key = key,
                JsonKey = jsonKey,
                DefaultValueLiteral = defaultLiteral,
                ContainingNamespace = containingNamespace,
                IsUnsupportedType = false
            };
        }

        // Reproduces ClassicUO.Configuration.ProfileJsonContext.SnakeCaseNamingPolicy exactly so the JSON
        // import reads the same keys the old profile.json was written with.
        private static string ToSnakeCase(string name)
        {
            var sb = new StringBuilder(name.Length + 8);
            for (int i = 0; i < name.Length; i++)
            {
                char c = name[i];
                if (i > 0 && char.IsUpper(c))
                    sb.Append('_');
                sb.Append(c);
            }
            return sb.ToString().ToLowerInvariant();
        }

        private static string GetPrimitiveTypeName(SpecialType st)
        {
            switch (st)
            {
                case SpecialType.System_Boolean: return "bool";
                case SpecialType.System_Byte:    return "byte";
                case SpecialType.System_SByte:   return "sbyte";
                case SpecialType.System_Int16:   return "short";
                case SpecialType.System_UInt16:  return "ushort";
                case SpecialType.System_Int32:   return "int";
                case SpecialType.System_UInt32:  return "uint";
                case SpecialType.System_Int64:   return "long";
                case SpecialType.System_UInt64:  return "ulong";
                case SpecialType.System_Single:  return "float";
                case SpecialType.System_Double:  return "double";
                case SpecialType.System_String:  return "string";
                default:                         return null;
            }
        }

        private static bool IsSupportedType(string typeName)
        {
            if (typeName == null) return false;
            switch (typeName)
            {
                case "bool":
                case "byte":
                case "sbyte":
                case "short":
                case "ushort":
                case "int":
                case "uint":
                case "long":
                case "ulong":
                case "float":
                case "double":
                case "string":
                    return true;
                default:
                    return false;
            }
        }

        private static string BuildDefaultLiteral(string typeName, object value)
        {
            if (value == null)
            {
                if (typeName == "string") return "null";
                return GetTypeDefault(typeName);
            }

            // Attribute constants may be boxed as a different primitive than the property type
            // (e.g. an int literal for a ushort property, or a float literal for a double property),
            // so convert explicitly rather than unboxing to a fixed type.
            switch (typeName)
            {
                case "bool":   return System.Convert.ToBoolean(value) ? "true" : "false";
                case "float":  return ((float)System.Convert.ToDouble(value)).ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f";
                case "double": return System.Convert.ToDouble(value).ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "d";
                case "uint":   return System.Convert.ToUInt32(value) + "u";
                case "long":   return System.Convert.ToInt64(value) + "L";
                case "ulong":  return System.Convert.ToUInt64(value) + "UL";
                case "string": return "\"" + value.ToString().Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
                default:       return System.Convert.ToInt64(value).ToString(System.Globalization.CultureInfo.InvariantCulture);
            }
        }

        private static string BuildEnumDefaultLiteral(string enumTypeName, object value)
        {
            if (value == null)
                return $"default({enumTypeName})";

            // Attribute stores the enum's underlying constant (boxed). Cast it back to the enum type.
            return $"({enumTypeName}){System.Convert.ToInt64(value)}";
        }

        private static string GetTypeDefault(string typeName)
        {
            switch (typeName)
            {
                case "bool":   return "false";
                case "string": return "null";
                case "float":  return "0f";
                case "double": return "0d";
                case "uint":   return "0u";
                case "long":   return "0L";
                case "ulong":  return "0UL";
                default:       return "0";
            }
        }

        // Map scope ordinal to SettingsScope name: Char=0, Account=1, Server=2, Global=3
        private static string ScopeName(int ordinal)
        {
            switch (ordinal)
            {
                case 0:  return "Char";
                case 1:  return "Account";
                case 2:  return "Server";
                case 3:  return "Global";
                default: return "Global";
            }
        }

        // Returns a boolean expression that parses rawVar into outVar (declared inline), or null when the
        // value needs no parsing (string) and can be assigned directly.
        private static string ParseCondition(SqlSettingModel m, string rawVar, string outVar)
        {
            if (m.IsEnum)
                return $"System.Enum.TryParse<{m.TypeName}>({rawVar}, out var {outVar})";

            switch (m.TypeName)
            {
                case "bool":   return $"bool.TryParse({rawVar}, out bool {outVar})";
                case "byte":   return $"byte.TryParse({rawVar}, out byte {outVar})";
                case "sbyte":  return $"sbyte.TryParse({rawVar}, out sbyte {outVar})";
                case "short":  return $"short.TryParse({rawVar}, out short {outVar})";
                case "ushort": return $"ushort.TryParse({rawVar}, out ushort {outVar})";
                case "int":    return $"int.TryParse({rawVar}, out int {outVar})";
                case "uint":   return $"uint.TryParse({rawVar}, out uint {outVar})";
                case "long":   return $"long.TryParse({rawVar}, out long {outVar})";
                case "ulong":  return $"ulong.TryParse({rawVar}, out ulong {outVar})";
                case "float":  return $"float.TryParse({rawVar}, out float {outVar})";
                case "double": return $"double.TryParse({rawVar}, out double {outVar})";
                case "string": return null; // no TryParse needed
                default:       return null;
            }
        }

        private static bool IsNonDefaultValue(SqlSettingModel m)
        {
            string literal = m.DefaultValueLiteral;

            if (m.IsEnum)
                return literal != $"({m.TypeName})0" && !literal.StartsWith("default(");

            switch (m.TypeName)
            {
                case "bool":   return literal == "true";
                case "string": return literal != "null" && literal != "\"\"";
                default:       return literal != "0" && literal != "0f" && literal != "0d"
                                   && literal != "0u" && literal != "0L" && literal != "0UL";
            }
        }

        private static void Generate(SourceProductionContext spc, ImmutableArray<SqlSettingModel> models)
        {
            if (models.IsDefaultOrEmpty)
                return;

            // Report diagnostics for unsupported types
            foreach (SqlSettingModel m in models.Where(x => x.IsUnsupportedType))
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "CUOSG003",
                        "Unsupported SQL setting type",
                        $"Property '{m.PropertyName}' has unsupported type '{m.TypeName}' for [SqlSetting].",
                        "ClassicUO.SourceGenerators",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None));
            }

            var valid = models.Where(x => !x.IsUnsupportedType).ToImmutableArray();
            if (valid.IsEmpty)
                return;

            // Check for duplicate scope+key
            var seen = new HashSet<string>();
            foreach (SqlSettingModel m in valid)
            {
                string combo = $"{m.ScopeOrdinal}:{m.Key}";
                if (!seen.Add(combo))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CUOSG004",
                            "Duplicate SQL setting key",
                            $"Duplicate key '{m.Key}' in scope '{ScopeName(m.ScopeOrdinal)}' on property '{m.PropertyName}'.",
                            "ClassicUO.SourceGenerators",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        Location.None));
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine("using ClassicUO.Game;");
            sb.AppendLine("using ClassicUO.Game.Managers;");
            sb.AppendLine();
            sb.AppendLine("namespace ClassicUO.Configuration");
            sb.AppendLine("{");
            sb.AppendLine("    public sealed partial class Profile");
            sb.AppendLine("    {");

            // When true, the generated setters skip persisting back to SQLite. Set while bulk-loading values
            // that already came from SQLite so hydration does not write them straight back.
            sb.AppendLine("        private bool _suppressSqlPersist;");
            sb.AppendLine();

            // Properties
            foreach (SqlSettingModel m in valid)
            {
                string scopeName = ScopeName(m.ScopeOrdinal);
                sb.AppendLine($"        public partial {m.TypeName} {m.PropertyName}");
                sb.AppendLine("        {");
                sb.AppendLine("            get;");
                sb.AppendLine("            set");
                sb.AppendLine("            {");
                sb.AppendLine("                if (SetProperty(ref field, value) && !_suppressSqlPersist)");
                sb.AppendLine($"                    _ = Client.Settings?.SetAsync(SettingsScope.{scopeName}, \"{m.Key}\", value);");
                sb.AppendLine("            }");

                if (IsNonDefaultValue(m))
                    sb.AppendLine($"        }} = {m.DefaultValueLiteral};");
                else
                    sb.AppendLine("        }");

                sb.AppendLine();
            }

            // Group by scope ordinal
            var byScope = valid.GroupBy(m => m.ScopeOrdinal).ToDictionary(g => g.Key, g => g.ToList());

            // Bulk dict loaders for every scope (Global, Account, Server, Char).
            foreach (int scopeOrdinal in new[] { 3, 1, 2, 0 })
            {
                if (!byScope.TryGetValue(scopeOrdinal, out List<SqlSettingModel> group))
                    continue;

                string scopeName = ScopeName(scopeOrdinal);
                sb.AppendLine($"        internal void LoadGenerated{scopeName}SqlSettings(System.Collections.Generic.Dictionary<string, string> kvp)");
                sb.AppendLine("        {");
                sb.AppendLine("            _suppressSqlPersist = true;");
                sb.AppendLine("            try");
                sb.AppendLine("            {");

                foreach (SqlSettingModel m in group)
                {
                    string rawVar = $"_raw_{m.PropertyName}";
                    sb.AppendLine($"                if (kvp.TryGetValue(\"{m.Key}\", out string {rawVar}))");
                    EmitAssignFromRaw(sb, m, rawVar, "                    ");
                }

                sb.AppendLine("            }");
                sb.AppendLine("            finally");
                sb.AppendLine("            {");
                sb.AppendLine("                _suppressSqlPersist = false;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // One-time import from the legacy profile.json document into SQLite. Assigning through each
            // setter persists the value via Client.Settings.SetAsync.
            sb.AppendLine("        internal void MigrateJsonToSql(JsonDocument doc)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (doc == null) return;");
            sb.AppendLine("            JsonElement root = doc.RootElement;");
            sb.AppendLine("            if (root.ValueKind != JsonValueKind.Object) return;");
            foreach (SqlSettingModel m in valid)
            {
                string elemVar = $"_e_{m.PropertyName}";
                string rawVar = $"_raw_{m.PropertyName}";
                sb.AppendLine($"            if (root.TryGetProperty(\"{m.JsonKey}\", out JsonElement {elemVar}) && {elemVar}.ValueKind != JsonValueKind.Null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                string {rawVar} = {elemVar}.ValueKind == JsonValueKind.String ? {elemVar}.GetString() : {elemVar}.GetRawText();");
                EmitAssignFromRaw(sb, m, rawVar, "                ");
                sb.AppendLine("            }");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("Profile.SqlSettings.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // Emits a single statement that assigns rawVar into the property (with parsing as needed).
        private static void EmitAssignFromRaw(StringBuilder sb, SqlSettingModel m, string rawVar, string indent)
        {
            string outVar = $"_v_{m.PropertyName}";
            string cond = ParseCondition(m, rawVar, outVar);
            if (cond == null)
            {
                // string: direct assign
                sb.AppendLine($"{indent}{m.PropertyName} = {rawVar};");
            }
            else
            {
                sb.AppendLine($"{indent}if ({cond}) {m.PropertyName} = {outVar};");
            }
        }
    }

    internal class SqlSettingModel
    {
        public string PropertyName { get; set; }
        public string TypeName { get; set; }
        public int ScopeOrdinal { get; set; }
        public string Key { get; set; }
        public string JsonKey { get; set; }
        public string DefaultValueLiteral { get; set; }
        public string ContainingNamespace { get; set; }
        public bool IsEnum { get; set; }
        public bool IsUnsupportedType { get; set; }
    }
}
